package com.alderfall.game;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.nio.file.*;
import java.util.*;
import java.util.List;
import javax.imageio.ImageIO;

/** Validate every catalog ability and export the exact runtime VFX renderer for the local gallery. */
public final class MonsterVfxReview {
    static final Path OUT = Path.of("tools/reviews/characters/monster-vfx");
    static final Map<String, MonsterAbilityVfx.Profile> profiles = new TreeMap<>();
    static String quote(String s) { return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""; }
    public static void main(String[] args) throws Exception {
        Files.createDirectories(OUT);
        AssetStore assets = new AssetStore(Path.of("assets"));
        StringBuilder js = new StringBuilder("// Generated by MonsterVfxReview; presentation shares MonsterAbilityVfx.draw.\nwindow.monsterVfx = {\n");
        StringBuilder audit = new StringBuilder("monster\tsprite\tability\tgameplay_effect\tvfx\tmotion\n");
        int count = 0;
        var schedule = Battle.class.getDeclaredMethod("scheduleMonsterAbility", Actor.class, MonsterAbility.class);
        schedule.setAccessible(true);
        for (String sprite : MonsterAttackAnimations.SPRITES.stream().sorted().toList()) {
            js.append(quote(sprite)).append(":[");
            LinkedHashMap<String, MonsterAbilityVfx.Profile> entries = new LinkedHashMap<>();
            entries.put("Basic attack", MonsterAbilityVfx.basic(sprite));
            for (var spec : GameData.MONSTERS.values()) if (spec.sprite().equals(sprite)) {
                List<MonsterAbility> abilities = new ArrayList<>(MonsterAbilities.forMonster(spec));
                if (Battle.isBossSpec(spec)) abilities.addAll(MonsterAbilities.bossAbilitiesFor(spec, 3));
                for (var ability : abilities) {
                    var profile = MonsterAbilityVfx.forAbility(sprite, ability);
                    require((ability.kind() == MonsterAbility.Kind.BUFF) == (profile.motion() == MonsterAbilityVfx.Motion.SELF), "Buff targeting " + ability.name());
                    Actor player = new Actor("Review player", "class_knight", "Knight", 100, 50, 10, 5);
                    Battle battle = new Battle(player,List.of(),List.of(spec),new Random(1),'g',"overworld");
                    Actor enemy = battle.enemies().get(0);
                    schedule.invoke(battle,enemy,ability);
                    BattleActionAnimation animation = battle.activeAnimation();
                    require(animation != null && profile.equals(animation.monsterVisual()), "Runtime mapping " + ability.name());
                    require(animation.effectKind.equals(ability.effect()), "Changed gameplay effect " + ability.name());
                    require((animation.target == enemy) == (ability.kind() == MonsterAbility.Kind.BUFF), "Runtime target " + ability.name());
                    require(MonsterAttackAnimations.playsAttack(animation,enemy) == (ability.kind() == MonsterAbility.Kind.DAMAGE), "Buff attack pose " + ability.name());
                    entries.put(spec.name() + " / " + ability.name(), profile);
                    audit.append(spec.key()).append('\t').append(sprite).append('\t').append(ability.name()).append('\t').append(ability.effect()).append('\t').append(profile.sprite()).append('\t').append(profile.motion()).append('\n');
                    count++;
                }
            }
            boolean comma = false;
            for (var e : entries.entrySet()) {
                if (comma) js.append(','); comma = true;
                profiles.put(e.getValue().id(),e.getValue());
                js.append("{name:").append(quote(e.getKey())).append(",id:").append(quote(e.getValue().id())).append(",motion:").append(quote(e.getValue().motion().name())).append('}');
            }
            js.append("],\n");
        }
        js.append("};\n");
        for (var profile : profiles.values()) {
            require(assets.assetNames().contains(profile.sprite()+"_anim"), "Missing authored VFX " + profile.sprite());
            BufferedImage strip = new BufferedImage(160*24,160,BufferedImage.TYPE_INT_ARGB);
            Graphics2D g = strip.createGraphics();
            for (int f=0; f<24; f++) {
                double t=f/24.0; int phase=t<.4?0:t<.6?1:2;
                double p=phase==0?t/.4:phase==1?(t-.4)/.2:(t-.6)/.4;
                Graphics2D cell=(Graphics2D)g.create();cell.translate(f*160,0);cell.scale(.5,.5);cell.clipRect(0,0,320,320);
                MonsterAbilityVfx.draw(cell,assets,profile,new int[]{245,205},new int[]{80,205},phase,p);cell.dispose();
            }
            g.dispose();ImageIO.write(strip,"png",OUT.resolve(profile.id()+".png").toFile());
        }
        // Review regressions: contact effects, water identity, and elemental status semantics.
        var eel=MonsterAbilities.forMonster(GameData.MONSTERS.get("river_eel")).get(0);
        require(MonsterAbilityVfx.forAbility("river_eel",eel).sprite().equals("fx_water_jet_unique"),"Current Lash water");
        require(eel.effect().equals("acid"),"Presentation changed gameplay");
        Files.writeString(OUT.resolve("../monster-vfx.js"),js);
        Files.writeString(OUT.resolve("ability-audit.tsv"),audit);
        String result="PASS: 58 sprites, " + count + " catalog and boss ability mappings, " + profiles.size() + " existing animated VFX presentations; self-buffs and assets verified.\n";
        Files.writeString(OUT.resolve("verification.txt"),result);System.out.print(result);
    }
    static void require(boolean condition,String message) { if(!condition)throw new IllegalStateException(message); }
}
