from __future__ import annotations


MONSTERS = {
    "slime": {"name": "Bog Slime", "hp": 24, "attack": 7, "defense": 1, "xp": 8, "gold": 4, "loot": {"potion_small": 12, "traveler_cloak": 4}},
    "wolf": {"name": "Grey Wolf", "hp": 32, "attack": 10, "defense": 2, "xp": 12, "gold": 7, "loot": {"potion_small": 8, "hunter_knife": 3}},
    "bat": {"name": "Cave Bat", "hp": 22, "attack": 9, "defense": 1, "xp": 10, "gold": 5, "loot": {"ether": 6, "mana_stone": 2}},
    "skeleton": {"name": "Restless Skeleton", "hp": 42, "attack": 12, "defense": 3, "xp": 18, "gold": 12, "loot": {"ether": 10, "iron_sword": 5}},
    "goblin": {"name": "Goblin Raider", "hp": 36, "attack": 11, "defense": 2, "xp": 15, "gold": 10, "loot": {"potion_small": 14, "guard_tonic": 5, "iron_ring": 5}},
    "goblin_scout": {"name": "Goblin Scout", "sprite": "goblin_scout", "hp": 30, "attack": 10, "defense": 1, "xp": 13, "gold": 8, "loot": {"potion_small": 10, "hunter_knife": 3}},
    "goblin_archer": {"name": "Goblin Archer", "sprite": "goblin_archer", "hp": 34, "attack": 13, "defense": 1, "xp": 17, "gold": 12, "loot": {"ash_bow": 3, "potion_small": 8}},
    "goblin_trapper": {"name": "Goblin Trapper", "sprite": "goblin_trapper", "hp": 42, "attack": 14, "defense": 3, "xp": 24, "gold": 18, "loot": {"guard_tonic": 8, "battle_kit": 4}},
    "goblin_skirmisher": {"name": "Goblin Skirmisher", "sprite": "goblin_skirmisher", "hp": 48, "attack": 16, "defense": 4, "xp": 28, "gold": 22, "loot": {"iron_sword": 4, "iron_ring": 4}},
    "goblin_shaman": {"name": "Goblin Shaman", "sprite": "goblin_shaman", "hp": 52, "attack": 18, "defense": 3, "xp": 36, "gold": 32, "loot": {"ether": 12, "mana_stone": 5}},
    "hobgoblin_guard": {"name": "Hobgoblin Guard", "sprite": "hobgoblin_guard", "hp": 76, "attack": 21, "defense": 7, "xp": 48, "gold": 42, "loot": {"iron_mail": 7, "guard_tonic": 12}},
    "goblin_warlord": {"name": "Goblin Warlord", "sprite": "goblin_warlord", "hp": 92, "attack": 25, "defense": 8, "xp": 70, "gold": 68, "loot": {"warrior_brooch": 8, "steel_sword": 5}},
    "goblin_king": {"name": "Goblin King", "sprite": "goblin_king", "hp": 132, "attack": 31, "defense": 10, "xp": 110, "gold": 120, "loot": {"warrior_brooch": 20, "enchanted_blade": 8, "battle_kit": 25}},
    "spider": {"name": "Cave Spider", "hp": 52, "attack": 14, "defense": 4, "xp": 23, "gold": 16, "loot": {"potion_large": 8, "leather_vest": 5}},
    "wraith": {"name": "Ash Wraith", "hp": 58, "attack": 17, "defense": 4, "xp": 30, "gold": 21, "loot": {"mage_robes": 6, "warding_seal": 3}},
    "orc": {"name": "Orc Brute", "hp": 66, "attack": 18, "defense": 5, "xp": 34, "gold": 28, "loot": {"iron_mail": 6, "steel_sword": 4}},
    "thornling": {"name": "Briar Thornling", "hp": 44, "attack": 13, "defense": 4, "xp": 20, "gold": 13, "loot": {"guard_tonic": 7, "vitality_charm": 4}},
    "sand_stalker": {"name": "Sand Stalker", "hp": 62, "attack": 19, "defense": 5, "xp": 36, "gold": 30, "loot": {"ether": 8, "ash_bow": 5}},
    "ice_golem": {"name": "Ice Golem", "hp": 96, "attack": 25, "defense": 11, "xp": 72, "gold": 66, "loot": {"guard_tonic": 18, "potion_large": 12}},
    "bog_beast": {"name": "Bog Beast", "hp": 84, "attack": 23, "defense": 8, "xp": 58, "gold": 50, "loot": {"potion_large": 18}},
    "ember_imp": {"name": "Ember Imp", "hp": 54, "attack": 20, "defense": 4, "xp": 42, "gold": 36, "loot": {"ether": 12}},
    "dire_wolf": {"name": "Dire Wolf", "sprite": "wolf", "hp": 54, "attack": 16, "defense": 4, "xp": 28, "gold": 20, "loot": {"ranger_coat": 4}},
    "acid_slime": {"name": "Acid Slime", "sprite": "slime", "hp": 46, "attack": 15, "defense": 3, "xp": 24, "gold": 18, "loot": {"warding_seal": 3}},
    "shadow_bat": {"name": "Shadow Bat", "sprite": "bat", "hp": 40, "attack": 16, "defense": 3, "xp": 25, "gold": 19},
    "bone_knight": {"name": "Bone Knight", "sprite": "skeleton", "hp": 70, "attack": 20, "defense": 6, "xp": 40, "gold": 33},
    "venom_spider": {"name": "Venom Spider", "sprite": "spider", "hp": 74, "attack": 22, "defense": 6, "xp": 46, "gold": 40},
    "elder_wraith": {"name": "Elder Wraith", "sprite": "wraith", "hp": 82, "attack": 24, "defense": 7, "xp": 55, "gold": 48, "loot": {"enchanted_blade": 5, "silkweave_robes": 6}},
    "orc_champion": {"name": "Orc Champion", "sprite": "orc", "hp": 95, "attack": 26, "defense": 8, "xp": 68, "gold": 60, "loot": {"steel_plate": 7, "warrior_brooch": 8}},
    "frost_wolf": {"name": "Frost Wolf", "sprite": "wolf", "hp": 72, "attack": 21, "defense": 6, "xp": 48, "gold": 44, "loot": {"frost_staff": 5, "phoenix_feather": 3}},
    "crypt_revenant": {"name": "Crypt Revenant", "sprite": "skeleton", "hp": 88, "attack": 25, "defense": 8, "xp": 62, "gold": 54, "loot": {"star_staff": 5, "warden_plate": 4}},
    "night_stalker": {"name": "Night Stalker", "sprite": "bat", "hp": 64, "attack": 23, "defense": 7, "xp": 52, "gold": 45},
    "acid_broodmother": {"name": "Acid Broodmother", "sprite": "spider", "hp": 108, "attack": 29, "defense": 10, "xp": 82, "gold": 78, "loot": {"battle_kit": 35, "potion_large": 25}},
}
