package com.alderfall.game;

import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;

/** Read the real menu from incident through response; narration alone must have no effects. */
public final class NpcQuestStoryTest {
    private static int checks;
    private static final StringBuilder transcript = new StringBuilder("# Local quest conversations\n\n"
            + "Generated by `NpcQuestStoryTest`. Each numbered passage is advanced with Continue before responses appear. "
            + "Reading does not accept work or record a finding. Weekly requests keep their objective IDs and rewards.\n\n");

    public static void main(String[] args) throws Exception {
        GameConfig config = GameConfig.load(Path.of(""));
        GameState state = fresh(config);
        Method create = GameState.class.getDeclaredMethod("createWeeklyNpcQuest", Npc.class, String.class, int.class);
        create.setAccessible(true);
        Set<String> templates = new HashSet<>();
        for (String map : List.of("village_oakhaven", "city_highwall", "city_sanctum", "city_belltower", "city_riverside", "town_northwatch")) {
            Npc speaker = new Npc(map, "Sori Willowbend", "npc_lumberjack", 8, 8, List.of("I'm working."), null, null, NpcJob.woodcutter());
            check(NpcQuestStories.occupation(speaker).contains("timber"), "Speaker lost their actual profession");
            for (int block = 0; block < 16; block++) {
                Quest q = (Quest) create.invoke(state, speaker, "weekly_test_" + map + "_" + block, block);
                templates.add(q.title);
                check(!q.description.contains("has a witness") && !q.description.contains("needs rumor"), "Narrator placeholder survived");
                check(!q.activeProgressDialog().isBlank(), "Missing directions");
                var session = DialogueLibrary.startSession(speaker, q, "forest", 0, new Random(1));
                select(session, "Discuss " + q.title + ".");
                boolean export = map.equals("village_oakhaven");
                if (export) transcript.append("## ").append(q.title).append("\n\n");
                int pages = read(session, export);
                check(pages >= 3, "Local incident was flattened into one task card");
                check(!q.accepted && q.progress == 0 && q.observedStages.isEmpty(), "Listening accepted or completed work");
                check(session.optionLabels().stream().noneMatch(s -> s.contains("Why does this matter now") || s.contains("What still needs")), "Checklist menu survived");
                var story = NpcQuestStories.story(q);
                check(session.optionLabels().contains(story.question()), "Missing concrete background question");
                select(session, story.question());
                String answer = readText(session);
                check(answer.equals(story.background()), "Background reply answered a different subject");
                select(session, "And what worries you most?");
                check(readText(session).equals(story.concern()), "Personal stakes disappeared");
                select(session, "About helping you...");
                check(!session.optionLabels().equals(List.of("Continue")), "Returning to responses replayed the whole opening");
                var accept = session.optionPreviews().stream().filter(p -> p.effect().equals("quest:accept:" + q.id)).findFirst().orElseThrow();
                check(accept.label().equals(story.accept()), "Acceptance doesn't name the player's commitment");
                if (export) {
                    transcript.append("Background question: ").append(story.question()).append("\n\n")
                            .append(story.background()).append("\n\n")
                            .append("Commitment: ").append(story.accept()).append("\n\n")
                            .append("Directions: ").append(q.activeProgressDialog()).append("\n\n");
                }
                // A changed quest invalidates a previously visible acceptance, including during narration.
                int index = session.optionLabels().indexOf(story.accept());
                q.accepted = true;
                check(session.choose(index).effect().isEmpty(), "Stale acceptance executed");
                var resumed = DialogueLibrary.startSession(speaker, q, "forest", 0, new Random(1));
                select(resumed, "Discuss " + q.title + ".");
                check(readText(resumed).equals(story.waiting()), "Return conversation forgot the person's concern");
            }
        }
        check(templates.equals(Set.of("Stock for the Workshop", "Tools Taken from the Bench")),
                "Woodcutters received work outside their occupation: " + templates);
        Quest hay = state.quests.get("hay_for_horses");
        Npc joss = GameData.NPCS.stream().filter(n -> "hay_for_horses".equals(n.questId())).findFirst().orElseThrow();
        var session = DialogueLibrary.startSession(joss, hay, "forest", 0, new Random(1));
        select(session, "Discuss " + hay.title + ".");
        transcript.append("## Farmer Joss: Hay for the Watch\n\n");
        read(session, true);
        select(session, "Why are you feeding the watch's horses?");
        check(readText(session).contains("My daughter"), "Joss has no personal reason for helping the watch");
        Quest followup = (Quest) create.invoke(state, joss, "weekly_joss_followup", 0);
        check(followup.activeStartDialog().contains("Three sound bales"), "New request ignores the preceding help");
        testSave(config, state);
        testChapterLinks(state);
        Path output = Path.of(args.length == 0 ? "out-story-refinement/local-quest-conversations.md" : args[0]);
        Files.createDirectories(output.toAbsolutePath().getParent());
        Files.writeString(output, transcript);
        testBackstories(output.toAbsolutePath().getParent().resolve("npc-background-conversations.md"));
        System.out.println("NPC story and continuation checks passed: " + checks);
    }

    private static void testChapterLinks(GameState state) throws Exception {
        Method report = GameState.class.getDeclaredMethod("precedingQuestReport", Npc.class, Quest.class);
        report.setAccessible(true);
        for (String id : List.of("ms_wake_ashes", "aria_chain_1", "samir_chain_1")) {
            Quest prior = state.quests.get(id);
            Quest next = state.quests.get(prior.nextQuestId);
            Npc npc = GameData.NPCS.stream().filter(n -> id.equals(n.questId())).findFirst().orElseThrow();
            prior.completed = false;
            check(((String) report.invoke(state, npc, next)).isEmpty(), "Unplayed chapter supplied a recap");
            prior.completed = true;
            String lead = (String) report.invoke(state, npc, next);
            check(lead.equals(QuestNarrative.clean(prior.stages.getLast().completeDialog())), "Recap loses the completed outcome");
            var session = DialogueLibrary.startSession(npc, next, "road", 0, new Random(1), DialogueLibrary.DialogueContext.empty(), lead);
            select(session, "Discuss " + next.title + ".");
            check(readText(session).startsWith(lead), "New offer forgot what led to it");
            select(session, "How did our earlier work lead to this?");
            check(readText(session).contains(lead), "Cannot reread the causal link");
        }
    }

    private static void testBackstories(Path output) throws Exception {
        StringBuilder text = new StringBuilder("# Introductions and character backgrounds\n\n"
                + "Generated from `NpcBackstories`. First meetings introduce work and place. Public history and the reason for asking a stranger "
                + "precede the first quest's response menu. Personal companion disclosures require 20 relationship or completion of earlier work. "
                + "The background topics remain available to reread; they grant no approval or quest evidence.\n\n");
        int companions = 0, campaign = 0;
        for (Npc npc : GameData.NPCS) {
            var history = NpcBackstories.profile(npc);
            if (history == null) continue;
            Quest q = GameData.QUESTS.get(npc.questId()).copy();
            boolean companion = q.companionQuest();
            if (companion) companions++; else campaign++;
            var session = DialogueLibrary.startSession(npc, q, "road", 0, new Random(1));
            check(session.line().contains(history.greeting()), "First greeting assumes a relationship: " + npc.name());
            check(session.optionLabels().contains("We barely know each other. Why ask me?"), "Cannot question a stranger's request");
            check(session.optionLabels().contains("What has this work cost you personally?") != companion,
                    "Companion's private disclosure is not earned: " + npc.name());
            select(session, "How did you come to this work?");
            check(readText(session).equals(history.background()), "Biography isn't connected to its question");
            check(q.progress == 0 && q.observedStages.isEmpty(), "Backstory grants discoveries");
            if (companion) {
                var trusted = DialogueLibrary.startSession(npc, q, "road", 20, new Random(1));
                check(trusted.optionLabels().contains("What has this work cost you personally?"), "Trust doesn't open personal history");
                check(!trusted.optionLabels().contains("We barely know each other. Why ask me?"), "Established acquaintance still speaks as a stranger");
            }
            var offered = DialogueLibrary.startSession(npc, q, "road", 0, new Random(1));
            select(offered, "Discuss " + q.title + ".");
            String opening = readText(offered);
            check(opening.contains(history.background()) && opening.contains(history.reasonToAsk()), "First request omits its background: " + npc.name());
            text.append("## ").append(npc.name()).append("\n\n")
                    .append("First meeting: ").append(history.introduction()).append("\n\n")
                    .append("Background: ").append(history.background()).append("\n\n")
                    .append("Reason to ask the player: ").append(history.reasonToAsk()).append("\n\n")
                    .append(companion ? "After trust or shared work: " : "Personal concern: ").append(history.privateHistory()).append("\n\n");
        }
        check(companions == 9 && campaign == 13, "Missing cast profiles: " + companions + " companions, " + campaign + " campaign/local NPCs");
        Files.writeString(output, text);
    }

    private static void testSave(GameConfig config, GameState state) throws Exception {
        state.ensureWeeklyNpcQuests();
        Quest q = state.quests.values().stream().filter(quest -> quest.id.startsWith("weekly_") && quest.needed > 1).findFirst().orElseThrow();
        q.accepted = true;
        q.progress = 1;
        SaveSystem saves = new SaveSystem(Files.createTempDirectory(Path.of("out-story-refinement"), "npc-story-save-"));
        saves.save(state, "Local story in progress");
        GameState loaded = fresh(config);
        check(saves.load(loaded, state.currentSaveId), "Weekly quest save didn't load");
        Quest restored = loaded.quests.get(q.id);
        check(restored != null && restored.accepted && restored.progress == 1, "Dialogue rewrite reset existing work");
        check(restored.activeStartDialog().equals(q.activeStartDialog()), "The incident changed after reload");
        check(restored.rewardGold == q.rewardGold, "Dialogue rewrite changed rewards");
    }

    private static int read(DialogueLibrary.DialogueSession session, boolean export) {
        int pages = 0;
        do {
            check(pages++ < 12, "Unending conversation");
            if (export) transcript.append("Passage ").append(pages).append(": ").append(session.line()).append("\n\n");
            if (!session.optionLabels().equals(List.of("Continue"))) break;
            var effect = session.choose(0);
            check(effect.effect().isEmpty() && effect.relationshipDelta() == 0, "Continue executed an action");
        } while (true);
        return pages;
    }

    private static String readText(DialogueLibrary.DialogueSession session) {
        StringBuilder text = new StringBuilder(session.line());
        int pages = 0;
        while (session.optionLabels().equals(List.of("Continue"))) {
            check(pages++ < 12, "Unending answer");
            session.choose(0);
            text.append(' ').append(session.line());
        }
        return text.toString();
    }

    private static void select(DialogueLibrary.DialogueSession s, String label) {
        read(s, false);
        int i = s.optionLabels().indexOf(label);
        check(i >= 0, "Missing response: " + label);
        s.choose(i);
    }

    private static GameState fresh(GameConfig config) {
        GameState state = new GameState(config);
        state.chooseClass("Mage");
        while (state.mode == GameMode.STORY_INTRO) state.advanceStoryIntro();
        return state;
    }

    private static void check(boolean pass, String message) {
        checks++;
        if (!pass) throw new AssertionError(message);
    }
}
