package com.alderfall.game;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Named VFX identities. Gameplay effect keys remain unchanged for statuses, sound and damage. */
public final class ClassAbilityVfx {
    public enum Family { SLASH, PIERCE, BASH, FIRE, ICE, LIGHTNING, ARCANE, SHADOW, POISON, ROOT, HOLY, HEAL, WARD, VEIL }
    public record Profile(String name, String sheet, int cell, int columns, int rows,
                          Ability.AbilityKind kind, Family family, String baseEffect) {
        public boolean restorative() { return kind != Ability.AbilityKind.DAMAGE; }
        public boolean melee() { return !restorative() && (family == Family.SLASH || family == Family.BASH || family == Family.SHADOW); }
        public String poseKind() { return restorative() ? "ward" : melee() ? (family == Family.BASH ? "bash" : "slash") : family == Family.PIERCE ? "pierce" : "arcane"; }
        public int impactFrames() { return melee() || family == Family.PIERCE ? 30 : family == Family.LIGHTNING ? 34 : 48; }
    }
    public static final List<String> CLASSES = List.of("Knight", "Mage", "Ranger", "Cleric", "Rogue", "Battle Medic",
            "Ironwall", "Bladedancer", "Veilrunner", "Wildspeaker", "Sunwarden", "Thornbinder", "Stonebreaker", "Nightblade", "Grovekeeper");
    private static final Map<String, Profile> PROFILES = new LinkedHashMap<>();
    public static final Map<String, String> RETAINED = Map.ofEntries(
            Map.entry("Root Memory", "root_memory"),
            Map.entry("Mend", "mend_unique"),
            Map.entry("Grove Hymn", "grove_hymn"),
            Map.entry("Seraphic Hymn", "seraphic_hymn"),
            Map.entry("Thorn Lash", "thorn_lash_unique"),
            Map.entry("Briar Tempest", "briar_tempest_unique"),
            Map.entry("Glacier Prison", "glacier_prison_unique"),
            Map.entry("Ley Detonation", "ley_detonation"),
            Map.entry("Firebolt", "firebolt_unique"),
            Map.entry("Inferno Script", "inferno_script_unique"));
    static {
        add("Aegis Mend", "fx_class_knight_atlas_v3", 0, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Banner Guard", "fx_class_knight_atlas_v3", 1, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Banner Sweep", "fx_class_knight_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "cleave");
        add("Bulwark", "fx_class_knight_atlas_v3", 3, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Crown Splitter", "fx_class_knight_atlas_v3", 4, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "prismatic");
        add("Crownward Cleave", "fx_class_knight_atlas_v3", 5, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "cleave");
        add("Final Challenge", "fx_class_knight_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "final_challenge_unique");
        add("First Aid", "fx_class_knight_atlas_v3", 7, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Iron Refuge", "fx_class_knight_atlas_v3", 8, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Line Anchor", "fx_class_knight_atlas_v3", 9, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Lionheart Charge", "fx_class_knight_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "prismatic");
        add("Oathbound Bulwark", "fx_class_knight_atlas_v3", 11, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Power Strike", "fx_class_knight_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "impact");
        add("Riposte Promise", "fx_class_knight_atlas_v3", 13, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("Royal Cleave", "fx_class_knight_atlas_v3", 14, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "cleave");
        add("Royal Order", "fx_class_knight_atlas_v3", 15, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "prismatic");
        add("Second Wind", "fx_class_knight_atlas_v3", 16, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Shield Bash", "fx_class_knight_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Shieldbreaker", "fx_class_knight_atlas_v3", 18, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "strike");
        add("Unbroken Standard", "fx_class_knight_atlas_v3", 19, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("War Cry", "fx_class_knight_atlas_v3", 20, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Absolute Winter", "fx_class_mage_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.ICE, "glacier_prison_unique");
        add("Arcane Burst", "fx_class_mage_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "arcane");
        add("Astral Refuge", "fx_class_mage_atlas_v3", 2, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Astral Verdict", "fx_class_mage_atlas_v3", 3, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "arcane");
        add("Chain Spark", "fx_class_mage_atlas_v3", 4, 5, 5, Ability.AbilityKind.DAMAGE, Family.LIGHTNING, "stormline_volley_unique");
        add("Chaos Bloom", "fx_class_mage_atlas_v3", 5, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "chaos_bloom_unique");
        add("Comet Spiral", "fx_class_mage_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "arcane");
        add("Frost Lance", "fx_class_mage_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.ICE, "frost_lance_unique");
        add("Ley Reversal", "fx_class_mage_atlas_v3", 8, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "ley_reversal_unique");
        add("Mana Bloom", "fx_class_mage_atlas_v3", 9, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Meteor Thread", "fx_class_mage_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "prismatic");
        add("Phoenix Equation", "fx_class_mage_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.FIRE, "inferno_script_unique");
        add("Prismatic Collapse", "fx_class_mage_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "chaos_bloom_unique");
        add("Renewing Ward", "fx_class_mage_atlas_v3", 13, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Star Mantle", "fx_class_mage_atlas_v3", 14, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "arcane");
        add("Worldfire Sigil", "fx_class_mage_atlas_v3", 15, 5, 5, Ability.AbilityKind.DAMAGE, Family.FIRE, "prismatic");
        add("Camouflage Break", "fx_class_ranger_atlas_v3", 0, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Fang Chorus", "fx_class_ranger_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "beastcall_howl_unique");
        add("Field Salve", "fx_class_ranger_atlas_v3", 2, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Greenway Remedy", "fx_class_ranger_atlas_v3", 3, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Heartline Shot", "fx_class_ranger_atlas_v3", 4, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "heartline_shot_unique");
        add("Herbal Remedy", "fx_class_ranger_atlas_v3", 5, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Horizon Kill", "fx_class_ranger_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "heartline_shot_unique");
        add("Lockjaw Ground", "fx_class_ranger_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "snare_arrow_unique");
        add("Marked Shot", "fx_class_ranger_atlas_v3", 8, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "piercing_shot_unique");
        add("Pack Cover", "fx_class_ranger_atlas_v3", 9, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Piercing Shot", "fx_class_ranger_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "piercing_shot_unique");
        add("Pinning Volley", "fx_class_ranger_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "volley");
        add("Poison Arrow", "fx_class_ranger_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.POISON, "poison");
        add("Rain Volley", "fx_class_ranger_atlas_v3", 13, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "volley");
        add("Skyfang Barrage", "fx_class_ranger_atlas_v3", 14, 5, 5, Ability.AbilityKind.DAMAGE, Family.LIGHTNING, "stormline_volley_unique");
        add("Smoke Screen", "fx_class_ranger_atlas_v3", 15, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "smoke_veil_unique");
        add("Snare Arrow", "fx_class_ranger_atlas_v3", 16, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "snare_arrow_unique");
        add("Snarefield", "fx_class_ranger_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "snare_arrow_unique");
        add("Storm Volley", "fx_class_ranger_atlas_v3", 18, 5, 5, Ability.AbilityKind.DAMAGE, Family.LIGHTNING, "volley");
        add("Stormcaller Skyfang Barrage", "fx_class_ranger_atlas_v3", 19, 5, 5, Ability.AbilityKind.DAMAGE, Family.LIGHTNING, "stormline_volley_unique");
        add("Stormline Volley", "fx_class_ranger_atlas_v3", 20, 5, 5, Ability.AbilityKind.DAMAGE, Family.LIGHTNING, "stormline_volley_unique");
        add("Twin Fang", "fx_class_ranger_atlas_v3", 21, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "claw");
        add("Aegis Circle", "fx_class_cleric_atlas_v3", 0, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "aegis_circle_unique");
        add("Blessing", "fx_class_cleric_atlas_v3", 1, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Choir of Return", "fx_class_cleric_atlas_v3", 2, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "mercy_wellspring_unique");
        add("Confession Brand", "fx_class_cleric_atlas_v3", 3, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "holy");
        add("Consecrated Circle", "fx_class_cleric_atlas_v3", 4, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "radiant");
        add("Dawn Priest Dawnfall", "fx_class_cleric_atlas_v3", 5, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "radiant");
        add("Dawnfall", "fx_class_cleric_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "radiant");
        add("Final Absolution", "fx_class_cleric_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "radiant");
        add("Judgment Chorus", "fx_class_cleric_atlas_v3", 8, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "radiant");
        add("Mercy Guard", "fx_class_cleric_atlas_v3", 9, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "mercy_wellspring_unique");
        add("Mercy Wellspring", "fx_class_cleric_atlas_v3", 10, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "mercy_wellspring_unique");
        add("Pilgrim Light", "fx_class_cleric_atlas_v3", 11, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Radiant Bolt", "fx_class_cleric_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "radiant_bolt_unique");
        add("Reviving Chorus", "fx_class_cleric_atlas_v3", 13, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Sanctuary Pulse", "fx_class_cleric_atlas_v3", 14, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "aegis_circle_unique");
        add("Seraphic Spear", "fx_class_cleric_atlas_v3", 15, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "holy");
        add("Sunlit Aegis", "fx_class_cleric_atlas_v3", 16, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Ward Prayer", "fx_class_cleric_atlas_v3", 17, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Blackout Blades", "fx_class_rogue_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Cheap Shot", "fx_class_rogue_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "volley");
        add("Fan of Knives", "fx_class_rogue_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "claw");
        add("Kidney Shot", "fx_class_rogue_atlas_v3", 3, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "impact");
        add("King's Last Whisper", "fx_class_rogue_atlas_v3", 4, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Knife Storm", "fx_class_rogue_atlas_v3", 5, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "claw");
        add("Rogue Black Powder Cut", "fx_class_rogue_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "dust");
        add("Rogue Killing Angle", "fx_class_rogue_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Rogue Last Breath Contract", "fx_class_rogue_atlas_v3", 8, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Rogue Moonless Verdict", "fx_class_rogue_atlas_v3", 9, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Rogue Needle Riposte", "fx_class_rogue_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("Rogue Perfect Exit", "fx_class_rogue_atlas_v3", 11, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Rogue Ruin the Room", "fx_class_rogue_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.POISON, "poison");
        add("Rogue Shadow Double", "fx_class_rogue_atlas_v3", 13, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Shadowstep Cut", "fx_class_rogue_atlas_v3", 14, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Smoke Veil", "fx_class_rogue_atlas_v3", 15, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "smoke_veil_unique");
        add("Vanish Protocol", "fx_class_rogue_atlas_v3", 16, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("Venom Edge", "fx_class_rogue_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.POISON, "poison");
        add("Bone Saw Line", "fx_class_battle_medic_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "impact");
        add("Bone Saw Sweep", "fx_class_battle_medic_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "impact");
        add("Caustic Flask", "fx_class_battle_medic_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.POISON, "caustic_flask_unique");
        add("Emergency Mend", "fx_class_battle_medic_atlas_v3", 3, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Emergency Rotation", "fx_class_battle_medic_atlas_v3", 4, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "heal");
        add("Field Surgeon Miracle Triage", "fx_class_battle_medic_atlas_v3", 5, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Field Suture", "fx_class_battle_medic_atlas_v3", 6, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Hemostatic Strike", "fx_class_battle_medic_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "hemostatic_strike_unique");
        add("Last Stand Tonic", "fx_class_battle_medic_atlas_v3", 8, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Miracle Triage", "fx_class_battle_medic_atlas_v3", 9, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Painkiller Rotation", "fx_class_battle_medic_atlas_v3", 10, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Painkiller Wall", "fx_class_battle_medic_atlas_v3", 11, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Panacea Toss", "fx_class_battle_medic_atlas_v3", 12, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "panacea_toss_unique");
        add("Pressure Point Cascade", "fx_class_battle_medic_atlas_v3", 13, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "impact");
        add("Stabilize Party", "fx_class_battle_medic_atlas_v3", 14, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Stabilizer Emergency Rotation", "fx_class_battle_medic_atlas_v3", 15, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "ward");
        add("Sterile Rush", "fx_class_battle_medic_atlas_v3", 16, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Tonic Toss", "fx_class_battle_medic_atlas_v3", 17, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Trauma Ward", "fx_class_battle_medic_atlas_v3", 18, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Armor Patch", "fx_class_ironwall_atlas_v3", 0, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Battering Charge", "fx_class_ironwall_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Breaker Citadel Breaker", "fx_class_ironwall_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "citadel_protocol_unique");
        add("Breaker Ironquake", "fx_class_ironwall_atlas_v3", 3, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Citadel Breaker", "fx_class_ironwall_atlas_v3", 4, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "citadel_protocol_unique");
        add("Citadel Protocol", "fx_class_ironwall_atlas_v3", 5, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "citadel_protocol_unique");
        add("Fortress Oath", "fx_class_ironwall_atlas_v3", 6, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Gatecrash", "fx_class_ironwall_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Hold Line", "fx_class_ironwall_atlas_v3", 8, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Interpose", "fx_class_ironwall_atlas_v3", 9, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Ironquake", "fx_class_ironwall_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Living Rampart", "fx_class_ironwall_atlas_v3", 11, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "citadel_protocol_unique");
        add("Rampart Collapse", "fx_class_ironwall_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "cleave");
        add("Redoubt Protocol", "fx_class_ironwall_atlas_v3", 13, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Redoubt Signal", "fx_class_ironwall_atlas_v3", 14, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Shield Anchor", "fx_class_ironwall_atlas_v3", 15, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Shield Ram", "fx_class_ironwall_atlas_v3", 16, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "shield_ram_unique");
        add("Wallbreaker Slam", "fx_class_ironwall_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Warning Slam", "fx_class_ironwall_atlas_v3", 18, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "impact");
        add("Crescent Cut", "fx_class_bladedancer_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "dual_cut_unique");
        add("Dual Cut", "fx_class_bladedancer_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "dual_cut_unique");
        add("Finale Cut", "fx_class_bladedancer_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "prismatic");
        add("Finale of Knives", "fx_class_bladedancer_atlas_v3", 3, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Grace Step", "fx_class_bladedancer_atlas_v3", 4, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Mirror Step", "fx_class_bladedancer_atlas_v3", 5, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Rhythm Break", "fx_class_bladedancer_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("Ribbon Storm", "fx_class_bladedancer_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Silken Guard", "fx_class_bladedancer_atlas_v3", 8, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "dust");
        add("Silver Arc", "fx_class_bladedancer_atlas_v3", 9, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "cleave");
        add("Silver Black Powder Cut", "fx_class_bladedancer_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "dust");
        add("Silver Killing Angle", "fx_class_bladedancer_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Silver Last Breath Contract", "fx_class_bladedancer_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Silver Moonless Verdict", "fx_class_bladedancer_atlas_v3", 13, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Silver Needle Riposte", "fx_class_bladedancer_atlas_v3", 14, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("Silver Perfect Exit", "fx_class_bladedancer_atlas_v3", 15, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Silver Ruin the Room", "fx_class_bladedancer_atlas_v3", 16, 5, 5, Ability.AbilityKind.DAMAGE, Family.POISON, "poison");
        add("Silver Shadow Double", "fx_class_bladedancer_atlas_v3", 17, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Spinning Arc", "fx_class_bladedancer_atlas_v3", 18, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "cleave");
        add("Blindside", "fx_class_veilrunner_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Exit Wound", "fx_class_veilrunner_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Glass Smoke", "fx_class_veilrunner_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Hidden Route", "fx_class_veilrunner_atlas_v3", 3, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "dust");
        add("Hidden Wire", "fx_class_veilrunner_atlas_v3", 4, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "strike");
        add("Knife Rain", "fx_class_veilrunner_atlas_v3", 5, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "claw");
        add("Null Step", "fx_class_veilrunner_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Quick Cut", "fx_class_veilrunner_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("Shadow Salve", "fx_class_veilrunner_atlas_v3", 8, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "shadow_salve_unique");
        add("Smoke Bomb", "fx_class_veilrunner_atlas_v3", 9, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "smoke_veil_unique");
        add("Vanish Trick", "fx_class_veilrunner_atlas_v3", 10, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Veil Black Powder Cut", "fx_class_veilrunner_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "dust");
        add("Veil Killing Angle", "fx_class_veilrunner_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Veil Last Breath Contract", "fx_class_veilrunner_atlas_v3", 13, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Veil Moonless Verdict", "fx_class_veilrunner_atlas_v3", 14, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Veil Needle Riposte", "fx_class_veilrunner_atlas_v3", 15, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("Veil Perfect Exit", "fx_class_veilrunner_atlas_v3", 16, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Veil Ruin the Room", "fx_class_veilrunner_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.POISON, "poison");
        add("Veil Shadow Double", "fx_class_veilrunner_atlas_v3", 18, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Beastcall Howl", "fx_class_wildspeaker_atlas_v3", 0, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "beastcall_howl_unique");
        add("Bramble Wave", "fx_class_wildspeaker_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Briar Call", "fx_class_wildspeaker_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Briar Surge", "fx_class_wildspeaker_atlas_v3", 3, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Elderwood Judgment", "fx_class_wildspeaker_atlas_v3", 4, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "prismatic");
        add("Green Balm", "fx_class_wildspeaker_atlas_v3", 5, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Green Mend", "fx_class_wildspeaker_atlas_v3", 6, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Grove Chorus", "fx_class_wildspeaker_atlas_v3", 7, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Grove Shelter", "fx_class_wildspeaker_atlas_v3", 8, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Old Growth Veil", "fx_class_wildspeaker_atlas_v3", 9, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "nature");
        add("Thorn Dart", "fx_class_wildspeaker_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Wild Ancient Herdcall", "fx_class_wildspeaker_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "beastcall_howl_unique");
        add("Wild Briar Tempest", "fx_class_wildspeaker_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "briar_tempest_unique");
        add("Wild Canopy Circle", "fx_class_wildspeaker_atlas_v3", 13, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Wild Elderwood Judgment", "fx_class_wildspeaker_atlas_v3", 14, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Wild Old Growth Veil", "fx_class_wildspeaker_atlas_v3", 15, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "nature");
        add("Wild Petal Chorus", "fx_class_wildspeaker_atlas_v3", 16, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "primeval_bloom_unique");
        add("Wild Primeval Bloom", "fx_class_wildspeaker_atlas_v3", 17, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "primeval_bloom_unique");
        add("Wild Verdant Sentence", "fx_class_wildspeaker_atlas_v3", 18, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "briar_tempest_unique");
        add("Censer Crush", "fx_class_sunwarden_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "impact");
        add("Dawn Mace", "fx_class_sunwarden_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "radiant");
        add("Dawn Shelter", "fx_class_sunwarden_atlas_v3", 2, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Gold Ward", "fx_class_sunwarden_atlas_v3", 3, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "halo_bastion_unique");
        add("Halo Bastion", "fx_class_sunwarden_atlas_v3", 4, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "halo_bastion_unique");
        add("Halo Bastion Halo Bastion", "fx_class_sunwarden_atlas_v3", 5, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "halo_bastion_unique");
        add("Hold Fast", "fx_class_sunwarden_atlas_v3", 6, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Lantern Aegis", "fx_class_sunwarden_atlas_v3", 7, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Lantern Blessing", "fx_class_sunwarden_atlas_v3", 8, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Lantern Refuge", "fx_class_sunwarden_atlas_v3", 9, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Noonflare", "fx_class_sunwarden_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.FIRE, "noonflare_unique");
        add("Noonstar Edict", "fx_class_sunwarden_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.FIRE, "noonflare_unique");
        add("Pilgrim Sun", "fx_class_sunwarden_atlas_v3", 12, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "radiant");
        add("Solar Flare", "fx_class_sunwarden_atlas_v3", 13, 5, 5, Ability.AbilityKind.DAMAGE, Family.FIRE, "noonflare_unique");
        add("Solar Judge Noonstar Edict", "fx_class_sunwarden_atlas_v3", 14, 5, 5, Ability.AbilityKind.DAMAGE, Family.FIRE, "noonflare_unique");
        add("Solar Judge Sunburst Road", "fx_class_sunwarden_atlas_v3", 15, 5, 5, Ability.AbilityKind.DAMAGE, Family.FIRE, "noonflare_unique");
        add("Sunburst Road", "fx_class_sunwarden_atlas_v3", 16, 5, 5, Ability.AbilityKind.DAMAGE, Family.FIRE, "noonflare_unique");
        add("Sunlit Mend", "fx_class_sunwarden_atlas_v3", 17, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Sunstrike", "fx_class_sunwarden_atlas_v3", 18, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "radiant");
        add("White Flame Verdict", "fx_class_sunwarden_atlas_v3", 19, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "holy");
        add("Barbed Bloom", "fx_class_thornbinder_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Bitter Salve", "fx_class_thornbinder_atlas_v3", 1, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Bramble Storm", "fx_class_thornbinder_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Bramble Verdict", "fx_class_thornbinder_atlas_v3", 3, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "bash");
        add("Root Burst", "fx_class_thornbinder_atlas_v3", 4, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Rooted Veil", "fx_class_thornbinder_atlas_v3", 5, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "nature");
        add("Thorn Ancient Herdcall", "fx_class_thornbinder_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "beastcall_howl_unique");
        add("Thorn Briar Tempest", "fx_class_thornbinder_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "briar_tempest_unique");
        add("Thorn Canopy Circle", "fx_class_thornbinder_atlas_v3", 8, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Thorn Elderwood Judgment", "fx_class_thornbinder_atlas_v3", 9, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Thorn Old Growth Veil", "fx_class_thornbinder_atlas_v3", 10, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "nature");
        add("Thorn Petal Chorus", "fx_class_thornbinder_atlas_v3", 11, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "primeval_bloom_unique");
        add("Thorn Primeval Bloom", "fx_class_thornbinder_atlas_v3", 12, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "primeval_bloom_unique");
        add("Thorn Snare", "fx_class_thornbinder_atlas_v3", 13, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "snare_arrow_unique");
        add("Thorn Tax", "fx_class_thornbinder_atlas_v3", 14, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Thorn Verdant Sentence", "fx_class_thornbinder_atlas_v3", 15, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "briar_tempest_unique");
        add("Thorn Wall", "fx_class_thornbinder_atlas_v3", 16, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Verdant Sentence", "fx_class_thornbinder_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "briar_tempest_unique");
        add("Armor Splitter", "fx_class_stonebreaker_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Avalanche Mountain Collapse", "fx_class_stonebreaker_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Avalanche Sentence", "fx_class_stonebreaker_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "cleave");
        add("Avalanche Swing", "fx_class_stonebreaker_atlas_v3", 3, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Bedrock Shelter", "fx_class_stonebreaker_atlas_v3", 4, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "stone_guard_unique");
        add("Continental Break", "fx_class_stonebreaker_atlas_v3", 5, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "titan_hammer_unique");
        add("Fault Reader Worldsplitter", "fx_class_stonebreaker_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "prismatic");
        add("Faultline Pick", "fx_class_stonebreaker_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Faultline Swing", "fx_class_stonebreaker_atlas_v3", 8, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Granite Brace", "fx_class_stonebreaker_atlas_v3", 9, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "stone_guard_unique");
        add("Granite Oath Granite Brace", "fx_class_stonebreaker_atlas_v3", 10, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "stone_guard_unique");
        add("Hammer Blow", "fx_class_stonebreaker_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Mountain Collapse", "fx_class_stonebreaker_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Quake Blow", "fx_class_stonebreaker_atlas_v3", 13, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Seismic Sweep", "fx_class_stonebreaker_atlas_v3", 14, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("Stone Guard", "fx_class_stonebreaker_atlas_v3", 15, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "stone_guard_unique");
        add("Stoneguard", "fx_class_stonebreaker_atlas_v3", 16, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Titan Hammer", "fx_class_stonebreaker_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "titan_hammer_unique");
        add("Worldsplitter", "fx_class_stonebreaker_atlas_v3", 18, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "worldsplitter");
        add("Dusk Black Powder Cut", "fx_class_nightblade_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "dust");
        add("Dusk Killing Angle", "fx_class_nightblade_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Dusk Last Breath Contract", "fx_class_nightblade_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Dusk Moonless Verdict", "fx_class_nightblade_atlas_v3", 3, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Dusk Needle Riposte", "fx_class_nightblade_atlas_v3", 4, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("Dusk Perfect Exit", "fx_class_nightblade_atlas_v3", 5, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Dusk Ruin the Room", "fx_class_nightblade_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.POISON, "poison");
        add("Dusk Shadow Double", "fx_class_nightblade_atlas_v3", 7, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Eclipse Flurry", "fx_class_nightblade_atlas_v3", 8, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Eclipse Rain", "fx_class_nightblade_atlas_v3", 9, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Execution Mark", "fx_class_nightblade_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "execution_mark");
        add("Fade", "fx_class_nightblade_atlas_v3", 11, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dark");
        add("Garrote Cut", "fx_class_nightblade_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Midnight Knife", "fx_class_nightblade_atlas_v3", 13, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Moonless Verdict", "fx_class_nightblade_atlas_v3", 14, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Night Mantle", "fx_class_nightblade_atlas_v3", 15, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "dust");
        add("Night Slash", "fx_class_nightblade_atlas_v3", 16, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("Nocturne Veil", "fx_class_nightblade_atlas_v3", 17, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "shield");
        add("Poison Kiss", "fx_class_nightblade_atlas_v3", 18, 5, 5, Ability.AbilityKind.DAMAGE, Family.POISON, "poison");
        add("Bloom Heal", "fx_class_grovekeeper_atlas_v3", 0, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Bloom Rite", "fx_class_grovekeeper_atlas_v3", 1, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Canopy Circle", "fx_class_grovekeeper_atlas_v3", 2, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "nature");
        add("Canopy Ward", "fx_class_grovekeeper_atlas_v3", 3, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Grove Ancient Herdcall", "fx_class_grovekeeper_atlas_v3", 4, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "beastcall_howl_unique");
        add("Grove Briar Tempest", "fx_class_grovekeeper_atlas_v3", 5, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "briar_tempest_unique");
        add("Grove Canopy Circle", "fx_class_grovekeeper_atlas_v3", 6, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Grove Elderwood Judgment", "fx_class_grovekeeper_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Grove Old Growth Veil", "fx_class_grovekeeper_atlas_v3", 8, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "nature");
        add("Grove Petal Chorus", "fx_class_grovekeeper_atlas_v3", 9, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "primeval_bloom_unique");
        add("Grove Primeval Bloom", "fx_class_grovekeeper_atlas_v3", 10, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "primeval_bloom_unique");
        add("Grove Verdant Sentence", "fx_class_grovekeeper_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "briar_tempest_unique");
        add("Petal Mend", "fx_class_grovekeeper_atlas_v3", 12, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Petal Tempest", "fx_class_grovekeeper_atlas_v3", 13, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Primeval Bloom", "fx_class_grovekeeper_atlas_v3", 14, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "primeval_bloom_unique");
        add("Renewing Grove", "fx_class_grovekeeper_atlas_v3", 15, 5, 5, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Thorn Whisper", "fx_class_grovekeeper_atlas_v3", 16, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Vine Flick", "fx_class_grovekeeper_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("Campfire Hymn", "fx_class_common_atlas_v3", 0, 3, 2, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Herbal Poultice", "fx_class_common_atlas_v3", 1, 3, 2, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Last Stand Camp", "fx_class_common_atlas_v3", 2, 3, 2, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("Quick Toss", "fx_class_common_atlas_v3", 3, 3, 2, Ability.AbilityKind.DAMAGE, Family.SLASH, "strike");
        add("Rallying Tune", "fx_class_common_atlas_v3", 4, 3, 2, Ability.AbilityKind.HEAL, Family.HEAL, "heal");
        add("Signal Flare", "fx_class_common_atlas_v3", 5, 3, 2, Ability.AbilityKind.DAMAGE, Family.FIRE, "ember");
        add("@knight/basic", "fx_class_attacks_1_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("@knight/heavy", "fx_class_attacks_1_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@knight/cleave", "fx_class_attacks_1_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("@knight/guard", "fx_class_attacks_1_atlas_v3", 3, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@knight/dodge", "fx_class_attacks_1_atlas_v3", 4, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@mage/basic", "fx_class_attacks_1_atlas_v3", 5, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "arcane");
        add("@mage/heavy", "fx_class_attacks_1_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "arcane");
        add("@mage/cleave", "fx_class_attacks_1_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.ARCANE, "arcane");
        add("@mage/guard", "fx_class_attacks_1_atlas_v3", 8, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@mage/dodge", "fx_class_attacks_1_atlas_v3", 9, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@ranger/basic", "fx_class_attacks_1_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "pierce");
        add("@ranger/heavy", "fx_class_attacks_1_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "pierce");
        add("@ranger/cleave", "fx_class_attacks_1_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.PIERCE, "pierce");
        add("@ranger/guard", "fx_class_attacks_1_atlas_v3", 13, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@ranger/dodge", "fx_class_attacks_1_atlas_v3", 14, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@cleric/basic", "fx_class_attacks_1_atlas_v3", 15, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "holy");
        add("@cleric/heavy", "fx_class_attacks_1_atlas_v3", 16, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "holy");
        add("@cleric/cleave", "fx_class_attacks_1_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "holy");
        add("@cleric/guard", "fx_class_attacks_1_atlas_v3", 18, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@cleric/dodge", "fx_class_attacks_1_atlas_v3", 19, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@rogue/basic", "fx_class_attacks_1_atlas_v3", 20, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("@rogue/heavy", "fx_class_attacks_1_atlas_v3", 21, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@rogue/cleave", "fx_class_attacks_1_atlas_v3", 22, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("@rogue/guard", "fx_class_attacks_1_atlas_v3", 23, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@rogue/dodge", "fx_class_attacks_1_atlas_v3", 24, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@battle_medic/basic", "fx_class_attacks_2_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@battle_medic/heavy", "fx_class_attacks_2_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@battle_medic/cleave", "fx_class_attacks_2_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@battle_medic/guard", "fx_class_attacks_2_atlas_v3", 3, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@battle_medic/dodge", "fx_class_attacks_2_atlas_v3", 4, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@ironwall/basic", "fx_class_attacks_2_atlas_v3", 5, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@ironwall/heavy", "fx_class_attacks_2_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@ironwall/cleave", "fx_class_attacks_2_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@ironwall/guard", "fx_class_attacks_2_atlas_v3", 8, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@ironwall/dodge", "fx_class_attacks_2_atlas_v3", 9, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@bladedancer/basic", "fx_class_attacks_2_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("@bladedancer/heavy", "fx_class_attacks_2_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@bladedancer/cleave", "fx_class_attacks_2_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.SLASH, "slash");
        add("@bladedancer/guard", "fx_class_attacks_2_atlas_v3", 13, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@bladedancer/dodge", "fx_class_attacks_2_atlas_v3", 14, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@veilrunner/basic", "fx_class_attacks_2_atlas_v3", 15, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("@veilrunner/heavy", "fx_class_attacks_2_atlas_v3", 16, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("@veilrunner/cleave", "fx_class_attacks_2_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("@veilrunner/guard", "fx_class_attacks_2_atlas_v3", 18, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@veilrunner/dodge", "fx_class_attacks_2_atlas_v3", 19, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@wildspeaker/basic", "fx_class_attacks_2_atlas_v3", 20, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("@wildspeaker/heavy", "fx_class_attacks_2_atlas_v3", 21, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("@wildspeaker/cleave", "fx_class_attacks_2_atlas_v3", 22, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("@wildspeaker/guard", "fx_class_attacks_2_atlas_v3", 23, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@wildspeaker/dodge", "fx_class_attacks_2_atlas_v3", 24, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@sunwarden/basic", "fx_class_attacks_3_atlas_v3", 0, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "holy");
        add("@sunwarden/heavy", "fx_class_attacks_3_atlas_v3", 1, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "holy");
        add("@sunwarden/cleave", "fx_class_attacks_3_atlas_v3", 2, 5, 5, Ability.AbilityKind.DAMAGE, Family.HOLY, "holy");
        add("@sunwarden/guard", "fx_class_attacks_3_atlas_v3", 3, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@sunwarden/dodge", "fx_class_attacks_3_atlas_v3", 4, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@thornbinder/basic", "fx_class_attacks_3_atlas_v3", 5, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("@thornbinder/heavy", "fx_class_attacks_3_atlas_v3", 6, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("@thornbinder/cleave", "fx_class_attacks_3_atlas_v3", 7, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("@thornbinder/guard", "fx_class_attacks_3_atlas_v3", 8, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@thornbinder/dodge", "fx_class_attacks_3_atlas_v3", 9, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@stonebreaker/basic", "fx_class_attacks_3_atlas_v3", 10, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@stonebreaker/heavy", "fx_class_attacks_3_atlas_v3", 11, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@stonebreaker/cleave", "fx_class_attacks_3_atlas_v3", 12, 5, 5, Ability.AbilityKind.DAMAGE, Family.BASH, "bash");
        add("@stonebreaker/guard", "fx_class_attacks_3_atlas_v3", 13, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@stonebreaker/dodge", "fx_class_attacks_3_atlas_v3", 14, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@nightblade/basic", "fx_class_attacks_3_atlas_v3", 15, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("@nightblade/heavy", "fx_class_attacks_3_atlas_v3", 16, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("@nightblade/cleave", "fx_class_attacks_3_atlas_v3", 17, 5, 5, Ability.AbilityKind.DAMAGE, Family.SHADOW, "dark");
        add("@nightblade/guard", "fx_class_attacks_3_atlas_v3", 18, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@nightblade/dodge", "fx_class_attacks_3_atlas_v3", 19, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
        add("@grovekeeper/basic", "fx_class_attacks_3_atlas_v3", 20, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("@grovekeeper/heavy", "fx_class_attacks_3_atlas_v3", 21, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("@grovekeeper/cleave", "fx_class_attacks_3_atlas_v3", 22, 5, 5, Ability.AbilityKind.DAMAGE, Family.ROOT, "nature");
        add("@grovekeeper/guard", "fx_class_attacks_3_atlas_v3", 23, 5, 5, Ability.AbilityKind.DEFEND, Family.WARD, "shield");
        add("@grovekeeper/dodge", "fx_class_attacks_3_atlas_v3", 24, 5, 5, Ability.AbilityKind.DEFEND, Family.VEIL, "dust");
    }
    private static void add(String name, String sheet, int cell, int columns, int rows, Ability.AbilityKind kind, Family family, String effect) {
        if (PROFILES.put(name, new Profile(name, sheet, cell, columns, rows, kind, family, effect)) != null)
            throw new IllegalStateException("Duplicate VFX identity: " + name);
    }
    public static Profile forName(String name) { return PROFILES.get(name); }
    public static Map<String, Profile> profiles() { return java.util.Collections.unmodifiableMap(PROFILES); }
    public static String attackName(String className, String mode) {
        String canonical = switch (className == null ? "" : className) {
            case "Medic" -> "Cleric";
            case "Archivist", "Snow Seer", "Marsh Witch" -> "Mage";
            case "Captain", "Roadwarden" -> "Knight";
            case "Frost Scout" -> "Ranger";
            case "Dune Guide" -> "Rogue";
            default -> CLASSES.contains(className == null ? "" : className) ? className : "Knight";
        };
        return "@" + canonical.toLowerCase(java.util.Locale.ROOT).replace(' ', '_') + "/" + mode;
    }
    private ClassAbilityVfx() {}
}

