package com.alderfall.game;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;

/** Inventory the entire quest catalog, including locations not yet individually rewritten. */
public final class DialoguePlaceAudit {
    public static void main(String[] args) throws Exception {
        Path output = Path.of(args.length == 0 ? "docs/quest-location-audit.md" : args[0]);
        StringBuilder rows = new StringBuilder();
        int quests = 0, stages = 0, unresolvedQuests = 0, unresolvedStages = 0;
        for (Quest q : GameData.QUESTS.values().stream().sorted(Comparator.comparing(quest -> quest.id)).toList()) {
            quests++;
            stages += q.stages.size();
            var unresolved = q.stages.stream().filter(DialoguePlaceAudit::indexedSite).toList();
            if (unresolved.isEmpty()) continue;
            unresolvedQuests++;
            unresolvedStages += unresolved.size();
            rows.append("| ").append(q.title).append(" (`").append(q.id).append("`) | ")
                    .append(q.companionQuest() ? q.chainOwnerId : q.mainStoryQuest() ? "Main" : "Side")
                    .append(" | ").append(unresolved.size()).append(" | ")
                    .append(unresolved.stream().map(s -> s.title() + ": `" + s.objectiveLocationKind()
                            + "[" + s.objectiveLocationIndex() + "]`").reduce((a, b) -> a + "; " + b).orElse(""))
                    .append(" |\n");
        }
        String text = "# Whole-catalog quest location audit\n\n"
                + "Generated by `DialoguePlaceAudit` from the current runtime quest catalog. This checks every quest stage's location binding; "
                + "it is a mechanical inventory, not a claim that every line has passed a human comprehension review.\n\n"
                + "Reviewed bindings: **" + quests + " quests / " + stages + " stages**. "
                + "Remaining generic indexed sites: **" + unresolvedQuests + " quests / " + unresolvedStages + " stages**.\n\n"
                + "All 26 main quests now have destinations in the [location library](../../Story%20premise/location-library.md). "
                + "The rows below still use a numbered camp, field, graveyard, or similar site. An NPC may name a place in speech, "
                + "but that does not guarantee its binding points there. Each row needs a named-place decision before directions are rewritten.\n\n"
                + "This inventory excludes local `story` anchors, explicit conversation contacts, and unlocated roaming hunts. "
                + "Exclusion does not certify their prose: introduce unfamiliar people and customs using the "
                + "[dialogue clarity rules](../../Story%20premise/dialogue-clarity-and-place-review.md).\n\n"
                + "| Quest | Owner / type | Indexed stages | Stage bindings to review |\n"
                + "| --- | --- | --- | --- |\n" + rows;
        Files.createDirectories(output.toAbsolutePath().getParent());
        Files.writeString(output, text);
        System.out.println("Location audit: " + quests + " quests, " + stages + " stages; "
                + unresolvedQuests + " quests retain " + unresolvedStages + " indexed stages.");
    }

    private static boolean indexedSite(Quest.QuestStage stage) {
        String kind = stage.objectiveLocationKind();
        return "overworld".equals(stage.objectiveMapId()) && !kind.isBlank()
                && !kind.equals("story") && !kind.equals("oathstead_camp") && !kind.startsWith("place:");
    }
}
